// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkGx6PvGy1TYajSZHlO7p3jX20iBrX7t0',
    appId: '1:334539854569:web:d2fbb7cfc554f078325678',
    messagingSenderId: '334539854569',
    projectId: 'mess-service-f117f',
    authDomain: 'mess-service-f117f.firebaseapp.com',
    storageBucket: 'mess-service-f117f.appspot.com',
    measurementId: 'G-MWLRQ11XD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYxLNzUhdEw3eHuVjvEAuSt_tyJUUNKsc',
    appId: '1:334539854569:android:34dee1ad78740524325678',
    messagingSenderId: '334539854569',
    projectId: 'mess-service-f117f',
    storageBucket: 'mess-service-f117f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9SMyl0bUCKUaLmscG9bFxq-tnO8b1rvQ',
    appId: '1:334539854569:ios:8abbd211cd2e4069325678',
    messagingSenderId: '334539854569',
    projectId: 'mess-service-f117f',
    storageBucket: 'mess-service-f117f.appspot.com',
    iosClientId: '334539854569-jhqmt47gn1ansugfqqvvpmsl5om0h3cb.apps.googleusercontent.com',
    iosBundleId: 'com.messService.messService',
  );
}
